on: 
 workflow_dispatch:
   inputs:
     logLevel:
       description: 'Log level'     
       required: true
       default: 'warning'
     tags:
       description: 'Test scenario tags'  
jobs:
 docit:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
   - name: Copy the Readmes
     run: |
       mkdir rpm
       cp interview.py rpm/
       
       
       
       
       
       











 
 

 
 
 
 
 
 
 
 
 
 
      
