on: 
 workflow_dispatch:
   inputs:
     logLevel:
       description: 'Log level'     
       required: true
       default: 'warning'
     tags:
       description: 'Test scenario tags'  
jobs:
 docit:
   runs-on: ubuntu-latest
   
   steps:
   
   - uses: actions/checkout@v4
   - name: Copy the Readmes
     working-directory: /home/runner/work/scripts/scripts
     run: |
       ls 
       mkdir rpm
       cp ./intervew.py rpm/
       
      
       
       
       
       
       











 
 

 
 
 
 
 
 
 
 
 
 
      
