on: 
 workflow_dispatch:
   inputs:
     logLevel:
       description: 'Log level'     
       required: true
       default: 'warning'
     tags:
       description: 'Test scenario tags'  
jobs:
 docit:
   runs-on: ubuntu-latest
   
   steps:
   
   #- uses: actions/checkout@v4
   - name: Copy the Readmes
     working-directory: ./scripts
     run: |
       mkdir rpm
       cp intervew.py rpm/
       
      
       
       
       
       
       











 
 

 
 
 
 
 
 
 
 
 
 
      
